services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=todo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "start"]

  postgres:
    image: postgres:14
    container_name: express-postgres
    restart: always
    environment:
      TZ: Asia/Seoul
      # POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - 5434:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: express-redis
    ports:
      - 6380:6379
    command: ["redis-server"]
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:

