openapi: 3.0.0
info:
    title: 'Express API with Swagger'
    version: 1.0.0
    description: 'Express 기반의 Todo API'
servers:
    -
        url: 'http://localhost:3000'
paths: {}
components: {}
tags: []
